// Currency symbols mapping
export const CURRENCY_SYMBOLS: Record<string, string> = {
    'USD': '$',
    'EUR': '€',
    'GBP': '£',
    'JPY': '¥',
    'AUD': 'A$',
    'CAD': 'C$',
    'CHF': 'CHF',
    'CNY': '¥',
    'INR': '₹',
    'BRL': 'R$',
    'ZAR': 'R',
    'MXN': '$',
    'SGD': 'S$',
    'HKD': 'HK$',
    'NZD': 'NZ$',
    'BDT': '৳',
    'PKR': '₨',
    'LKR': 'Rs',
    'NPR': 'Rs',
    'THB': '฿',
    'MYR': 'RM',
    'IDR': 'Rp',
    'PHP': '₱',
    'VND': '₫',
    'KRW': '₩',
    'TWD': 'NT$',
    'AED': 'د.إ',
    'SAR': '﷼',
    'ILS': '₪',
    'TRY': '₺',
    'RUB': '₽',
    'PLN': 'zł',
    'SEK': 'kr',
    'NOK': 'kr',
    'DKK': 'kr',
    'CZK': 'Kč',
    'HUF': 'Ft',
    'RON': 'lei',
    'BGN': 'лв',
    'HRK': 'kn',
    'EGP': 'E£',
    'NGN': '₦',
    'KES': 'KSh',
    'ETB': 'Br',
    'GHS': '₵',
    'TZS': 'TSh',
    'UGX': 'USh',
    'MAD': 'د.م.',
    'TND': 'د.ت',
    'DZD': 'د.ج',
    'IQD': 'ع.د',
    'JOD': 'د.ا',
    'LBP': 'ل.ل',
    'OMR': 'ر.ع.',
    'QAR': 'ر.ق',
    'KWD': 'د.ك',
    'BHD': 'د.ب',
    'ARS': '$',
    'CLP': '$',
    'COP': '$',
    'PEN': 'S/',
    'UYU': '$U',
    'BOB': 'Bs.',
    'PYG': '₲',
    'CRC': '₡',
    'GTQ': 'Q',
    'HNL': 'L',
    'NIO': 'C$',
    'PAB': 'B/.',
    'DOP': 'RD$',
    'JMD': 'J$',
    'BBD': 'Bds$',
    'BZD': 'BZ$',
    'TTD': 'TT$',
    'XCD': '$',
    'AWG': 'ƒ',
    'ANG': 'ƒ',
    'SRD': '$',
    'GYD': '$',
    'BMD': '$',
    'BAM': 'КМ',
    'RSD': 'дин.',
    'MKD': 'ден',
    'ALL': 'Lek',
    'ISK': 'kr',
    'MDL': 'lei',
    'UAH': '₴',
    'BYN': 'Br',
    'GEL': '₾',
    'AMD': '֏',
    'AZN': '₼',
    'KZT': '₸',
    'KGS': 'сом',
    'TJS': 'ЅМ',
    'TMT': 'm',
    'UZS': 'лв',
    'MNT': '₮',
    'MMK': 'K',
    'LAK': '₭',
    'KHR': '៛',
    'BND': 'B$',
    'FJD': 'FJ$',
    'PGK': 'K',
    'SBD': 'SI$',
    'VUV': 'Vt',
    'WST': 'T',
    'TOP': 'T$',
    'XPF': '₣',
    'NCF': '₣',
    'AOA': 'Kz',
    'MZN': 'MT',
    'MWK': 'MK',
    'ZMW': 'ZK',
    'BWP': 'P',
    'SZL': 'E',
    'LSL': 'L',
    'NAD': 'N$',
    'MGA': 'Ar',
    'MUR': '₨',
    'SCR': '₨',
    'DJF': 'Fdj',
    'ERN': 'Nfk',
    'SOS': 'Sh',
    'SLL': 'Le',
    'GMD': 'D',
    'GNF': 'FG',
    'LRD': '$',
    'CDF': 'FC',
    'RWF': 'RF',
    'BIF': 'FBu',
    'STN': 'Db',
    'XAF': 'FCFA',
    'XOF': 'CFA',
    'CVE': '$',
    'KMF': 'CF',
    'MOP': 'P',
    'BTN': 'Nu.',
    'AFN': '؋',
    'IRR': '﷼',
    'IQD': 'ع.د',
    'YER': '﷼',
    'SYP': '£',
    'LBP': 'ل.ل',
    'JOD': 'د.ا',
    'ILS': '₪',
    'PAB': 'B/.',
    'BND': 'B$',
    'KYD': '$',
    'FKP': '£',
    'GIP': '£',
    'SHP': '£',
    'GGP': '£',
    'JEP': '£',
    'IMP': '£',
    'TVD': '$',
    'CUC': '$',
    'CUP': '₱',
    'XAF': 'FCFA',
    'XOF': 'CFA',
    'XPF': '₣',
    'XCD': '$',
    'XDR': 'SDR',
    'XAG': 'oz t',
    'XAU': 'oz t',
    'XPD': 'oz t',
    'XPT': 'oz t',
};

export function formatCurrency(amount: number | string, currency: string = 'USD'): string {
    const symbol = CURRENCY_SYMBOLS[currency] || currency;
    const numAmount = typeof amount === 'string' ? parseFloat(amount) : amount;
    if (isNaN(numAmount)) {
        return `${symbol}0.00`;
    }
    return `${symbol}${numAmount.toFixed(2)}`;
}

export function formatCurrencyWithSign(amount: number | string, currency: string = 'USD', sign: '+' | '-' | '' = ''): string {
    const symbol = CURRENCY_SYMBOLS[currency] || currency;
    const numAmount = typeof amount === 'string' ? parseFloat(amount) : amount;
    if (isNaN(numAmount)) {
        return `${sign}${symbol}0.00`;
    }
    return `${sign}${symbol}${numAmount.toFixed(2)}`;
}

